FROM master-image

LABEL author="Patrick"

ARG USER
ARG BUILDKIT_STEP_LOG_MAX_SIZE

COPY --chown=$USER:$USER ../lib $HOME/lib
COPY --chown=$USER:$USER ../frontend/package.json $FRONTEND_HOME/package.json

USER $USER

WORKDIR $FRONTEND_HOME

RUN rm -rf yarn.lock .angular/cache* node_modules/lib
RUN yarn install

CMD npx ng serve --host 0.0.0.0 --poll=1000
# CMD tail -f /dev/null